spring:
  application:
    name: shoe-client
# eureka:
#   client:
#     serviceUrl:
#       defaultZone: http://18.233.226.216:8761/eureka/

  eureka.client.serviceUrl.defaultZone=http://54.86.134.223:8081/eureka/

